server:
    mode: "test"
    port: ":21009"

redis:
    db: 0 # defaults 0
    failover: false
    password: ""
    # master_name: "" # should enable when failover = true
    addrs:
        - "127.0.0.1:6379"
    size: 10
    network: "tcp"
    key_pairs: ""
