server:
    mode: "test"
    port: ":11009"

redis:
    db: 0 # defaults 0
    failover: false
    password: ""
    # master_name: "" # should enable when failover = true
    addrs:
        - "127.0.0.1:6379"
    size: 10
    network: "tcp"
    key_pairs: ""
session:
    max_age: 604800
proxy_config:
    files: '../config/proxy_*.yml'
